// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8qxAX8sXOG-RuU_UPxqPvTE5V9oyV3I4',
    appId: '1:807920090403:web:99a36385cdd0c3caeda096',
    messagingSenderId: '807920090403',
    projectId: 'sociall-app-b7268',
    authDomain: 'sociall-app-b7268.firebaseapp.com',
    storageBucket: 'sociall-app-b7268.appspot.com',
    measurementId: 'G-5PF4FLZCQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuY8xJZ6gD5voMoSJp7JaGFL43Ps0jq4o',
    appId: '1:807920090403:android:a9fbdd59f1b4cdd3eda096',
    messagingSenderId: '807920090403',
    projectId: 'sociall-app-b7268',
    storageBucket: 'sociall-app-b7268.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaBtJHy0aHF9oF_rmJjnZViGuIEI7i3kw',
    appId: '1:807920090403:ios:ab0a736782374c05eda096',
    messagingSenderId: '807920090403',
    projectId: 'sociall-app-b7268',
    storageBucket: 'sociall-app-b7268.appspot.com',
    iosBundleId: 'com.example.sociallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaBtJHy0aHF9oF_rmJjnZViGuIEI7i3kw',
    appId: '1:807920090403:ios:0a6edb9f4e710eeeeda096',
    messagingSenderId: '807920090403',
    projectId: 'sociall-app-b7268',
    storageBucket: 'sociall-app-b7268.appspot.com',
    iosBundleId: 'com.example.sociallApp.RunnerTests',
  );
}
